# Generated by Django 3.2.10 on 2022-01-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_avodha_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='desc',
            new_name='shop_location',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='name',
            new_name='shop_name',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='price',
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_type',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
