# Generated by Django 3.2.10 on 2022-01-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_avodha_app', '0002_auto_20220113_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop_location',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shop_type',
        ),
        migrations.AddField(
            model_name='shop',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
