# Generated by Django 3.2.10 on 2022-01-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_avodha_app', '0003_auto_20220114_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='img',
            field=models.ImageField(default=0, upload_to='pic'),
            preserve_default=False,
        ),
    ]
